defined? a

defined?(a)

defined? super_super_super_super_super_super_super_super_super_super_super_super_super_super_long

defined?(super_super_super_super_super_super_super_super_super_super_super_super_super_super_long)

defined?(
  super_super_super_super_super_super_super_super_super_super_super_super_super_super_long
)

defined?(a) # comment
