#!/usr/bin/env bash

diff src/parser.rb playground/parser.rb > /dev/null

if [ $? -eq 1 ]; then
  echo "playground/parser.rb out of sync with src/parser.rb"
  exit 1
fi

STAGED=$(git diff --cached --name-only)

if [ -n "$STAGED" ]; then
  echo "Some files are still staged in git"
  exit 1
fi

git subtree push --prefix playground heroku master
